# REST End point options for specifying properties

# /{application}/{profile}   - method used in this repo
# /{application}-{profile}.yml
# /{application}-{profile}.properties
# Remember no profile = default

# The properties in this file are global - all applications will get them

foo: bar